dist: debian
language: cpp
compiler: clang
addons:
  apt:
    packages:
    - clang
    - libboost-test-dev
    - libspdlog-dev
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -f -T firstWork-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -u zagumennovav:$BINTRAY_API_KEY "https://api.bintray.com/content/zagumennovav/otus-cpp/homework/$TRAVIS_BUILD_NUMBER/firstWork-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=buster;deb_component=main;deb_architecture=amd64;publish=1"
