dist: xenial
language: cpp
compiler: clang
addons:
  apt:
    packages:
    - libboost-test-dev
    - libspdlog-dev
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -f -T firstWork-0.0.3-Linux.deb -u ZagumennovAV:$BINTRAY_API_KEY "https://api.bintray.com/content/ZagumennovAV/otus-cpp/homework/3/firstWork-0.0.3-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
